name: Build and test nginx app
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker hub
        id: login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Install bundler for testing
        id: bundle
        run: apt-get install bundler
      - name: Install dependencies
        id: bundler_dependencies
        run: bundler install --gemfile=Gemfile
      - name: Build the image and test
        id: build
        run: bundler exec rspec --color --format documentation

